umap:
  n_components: 5
  n_neighbors: 15
  min_dist: 0.0
  random_state: 42

hdbscan:
  min_samples: 5
  gen_min_span_tree: True
  prediction_data: True

bertopic:
  calculate_probabilities: False
  verbose: True
  min_topic_size: 10
  min_similarity: 0.7

hardware: CPU

reddit:
  client_id: 'your_client_id'
  client_secret: 'your_client_secret'
  redirect_uri: 'your_redirect_uri'
  user_agent: 'your_user_agent'

lexicon:
  lexicon_filepath: data/NRC-Emotion-Intensity-Lexicon-v1.txt  